async function cadastrarMembro(){if(!window.isAdmin)return alert('Somente o administrador pode cadastrar integrantes.');const nome=document.getElementById('novo-nome').value.trim();if(!nome)return alert('Digite o nome.');try{await window.dbSet(window.dbRef(window.db,`membros_louvor/${chaveNome(nome)}`),{nome});await registrarAuditoria('membro_cadastrado',`${nome} cadastrado`);document.getElementById('novo-nome').value='';toast('Integrante cadastrado.')}catch(e){alert('Não foi possível cadastrar.')}}
async function removerMembro(nome){if(!window.isAdmin)return;if(!confirm(`Excluir ${nome} do cadastro? As chamadas antigas serão mantidas.`))return;try{await window.dbRemove(window.dbRef(window.db,`membros_louvor/${chaveNome(nome)}`));await registrarAuditoria('membro_excluido',`${nome} excluído do cadastro`)}catch(e){alert('Não foi possível excluir.')}}
async function editarMembro(nomeAtual){if(!window.isAdmin)return;const novo=(prompt('Novo nome do integrante:',nomeAtual)||'').trim();if(!novo||novo===nomeAtual)return;const novaChave=chaveNome(novo),chaveAntiga=chaveNome(nomeAtual);if(window.integrantesCadastrados?.[novaChave]&&novaChave!==chaveAntiga)return alert('Já existe um integrante com esse nome.');try{await window.dbSet(window.dbRef(window.db,`membros_louvor/${novaChave}`),{nome:novo});if(novaChave!==chaveAntiga)await window.dbRemove(window.dbRef(window.db,`membros_louvor/${chaveAntiga}`));await registrarAuditoria('membro_renomeado',`${nomeAtual} alterado para ${novo}`);toast('Nome atualizado. As chamadas antigas foram preservadas.')}catch(e){console.error(e);alert('Não foi possível alterar o nome.')}}
function renderizarListaCadastrados(){const termo=(document.getElementById('busca-membro')?.value||'').trim().toLowerCase(),todos=listaMembros(),arr=termo?todos.filter(n=>n.toLowerCase().includes(termo)):todos;document.getElementById('total-membros-badge').textContent=termo?`${arr.length}/${todos.length}`:todos.length;document.getElementById('hero-membros').textContent=`👥 ${todos.length} integrantes`;document.getElementById('lista-membros-cadastrados').innerHTML=arr.length?arr.map(n=>`<div class="manage-item"><strong>${esc(n)}</strong>${window.isAdmin?`<div class="member-actions"><button class="small-btn" onclick='editarMembro(${JSON.stringify(n)})'>✏️ Editar</button><button class="del" onclick='removerMembro(${JSON.stringify(n)})'>✕</button></div>`:''}</div>`).join(''):'<div class="muted center">Nenhum integrante encontrado.</div>'}

async function registrarAuditoria(acao,detalhe){if(!window.usuarioAtual)return;const ts=Date.now(),id=`${ts}_${Math.random().toString(36).slice(2,8)}`;try{await window.dbSet(window.dbRef(window.db,`auditoria_louvor/${id}`),{uid:window.usuarioAtual.uid,email:window.usuarioAtual.email||'',acao,detalhe,quando:new Date().toISOString()})}catch(e){}}
function renderAuditoria(){const box=document.getElementById('lista-auditoria');if(!box||!window.isAdmin)return;const arr=Object.values(window.auditoriaDados||{}).sort((a,b)=>(b.quando||'').localeCompare(a.quando||'')).slice(0,60);box.innerHTML=arr.length?arr.map(x=>`<div class="audit-item"><div><strong>${esc(x.acao||'Alteração')}</strong><div class="muted">${esc(x.detalhe||'')}</div></div><div class="muted" style="text-align:right">${esc(x.email||'')}<br>${x.quando?new Date(x.quando).toLocaleString('pt-BR'):''}</div></div>`).join(''):'<div class="muted center">Nenhum registro de auditoria ou regras ainda não publicadas.</div>'}
function renderPerfis(){const box=document.getElementById('lista-perfis');if(!box||!window.isAdmin)return;const perfis=window.perfisDados||{},uids=Object.keys(perfis);box.innerHTML=uids.length?uids.map(uid=>{const p=perfis[uid],atual=(window.rolesDados||{})[uid]||'responsavel';return `<div class="profile-item"><div><strong>${esc(p.email||uid)}</strong><div class="muted">UID: ${esc(uid.slice(0,10))}…</div></div><select style="width:145px" onchange='alterarRole(${JSON.stringify(uid)},this.value)'><option value="responsavel" ${atual==='responsavel'?'selected':''}>Responsável</option><option value="visualizacao" ${atual==='visualizacao'?'selected':''}>Visualização</option></select></div>`}).join(''):'<div class="muted center">Nenhum perfil disponível ou regras ainda não publicadas.</div>'}
async function alterarRole(uid,role){if(!window.isAdmin)return;try{await window.dbSet(window.dbRef(window.db,`roles_louvor/${uid}`),role);window.rolesDados??={};window.rolesDados[uid]=role;await registrarAuditoria('permissao_alterada',`Perfil ${uid.slice(0,8)} alterado para ${role}`);toast('Permissão atualizada.')}catch(e){alert('Não foi possível atualizar. Publique as regras avançadas do Firebase.')}}
async function carregarRolesAdmin(){if(!window.isAdmin)return;try{const s=await window.dbGet(window.dbRef(window.db,'roles_louvor'));window.rolesDados=s.val()||{};renderPerfis()}catch(e){}}

function baixarBackup(){if(!window.isAdmin)return;const backup={app:'Louvor_Pinhos',versao:2,geradoEm:new Date().toISOString(),membros_louvor:window.integrantesCadastrados||{},registros_louvor:window.todosOsDados||{}};const blob=new Blob([JSON.stringify(backup,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`backup-louvor-${hojeLocal()}.json`;a.click();URL.revokeObjectURL(url);registrarAuditoria('backup_exportado','Backup JSON baixado')}
async function restaurarBackup(){if(!window.isAdmin)return;const f=document.getElementById('arquivo-backup').files[0];if(!f)return alert('Selecione um arquivo JSON.');if(!confirm('ATENÇÃO: membros e chamadas atuais serão substituídos pelo backup. Continuar?'))return;try{const b=JSON.parse(await f.text());if(!b||typeof b.membros_louvor!=='object'||typeof b.registros_louvor!=='object')throw new Error('Formato inválido');await window.dbSet(window.dbRef(window.db,'membros_louvor'),b.membros_louvor);await window.dbSet(window.dbRef(window.db,'registros_louvor'),b.registros_louvor);await registrarAuditoria('backup_restaurado',`Backup de ${b.geradoEm||'data desconhecida'} restaurado`);toast('Backup restaurado com sucesso.')}catch(e){console.error(e);alert('Não foi possível restaurar. Verifique o arquivo e as permissões.')}}