window.todosOsDados={};window.integrantesCadastrados={};window.usuarioAtual=null;window.isAdmin=false;window.roleLouvor='visualizacao';window.auditoriaDados={};window.perfisDados={};
let statusSelecionado='presente',justificativaSelecionada='nao',rascunhoChamada={};
const ADMIN_EMAIL='icmpinhos@gmail.com';
function hojeLocal(){const d=new Date(),p=n=>String(n).padStart(2,'0');return `${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`}
const hoje=hojeLocal();document.getElementById('ensaio-data').value=hoje;document.getElementById('mes-relatorio').value=hoje.slice(0,7);document.getElementById('mes-dashboard').value=hoje.slice(0,7);document.getElementById('hero-data').textContent='📅 '+formatData(hoje);
if(localStorage.getItem('louvor_theme')==='dark')document.body.classList.add('dark-mode');

function resolverEmailLogin(usuario){const u=(usuario||'').trim().toLowerCase();return u==='admin'?ADMIN_EMAIL:(u.includes('@')?u:`${u}@frequencia-icm.app`)}
async function entrarNoApp(){const usuario=document.getElementById('login-usuario').value.trim(),senha=document.getElementById('login-senha').value,erro=document.getElementById('login-erro');erro.textContent='';if(!usuario||!senha){erro.textContent='Informe usuário e senha.';return}try{await window.firebaseSignIn(window.firebaseAuth,resolverEmailLogin(usuario),senha);document.getElementById('login-senha').value=''}catch(e){console.error(e);erro.textContent='Usuário ou senha inválidos.'}}
async function recuperarSenha(){const usuario=document.getElementById('login-usuario').value.trim(),erro=document.getElementById('login-erro');erro.textContent='';if(!usuario){erro.textContent='Digite seu usuário ou e-mail primeiro.';return}try{await window.firebaseResetPassword(window.firebaseAuth,resolverEmailLogin(usuario));erro.style.color='#146c3a';erro.textContent='E-mail de recuperação enviado. Confira sua caixa de entrada e spam.';setTimeout(()=>erro.style.color='',5000)}catch(e){console.error(e);erro.textContent='Não foi possível enviar a recuperação para este usuário.'}}
async function sairDoApp(){try{await window.firebaseSignOut(window.firebaseAuth)}catch(e){console.error(e)}}
function alternarTema(){const d=document.body.classList.toggle('dark-mode');localStorage.setItem('louvor_theme',d?'dark':'light')}
function alternarAba(nome,btn){document.querySelectorAll('.tab-btn').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab-content').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.getElementById('tab-'+nome).classList.add('active');if(nome==='dashboard')carregarDashboard();if(nome==='historico')renderHistorico();if(nome==='membros')renderizarListaCadastrados();if(nome==='config'){renderAuditoria();renderPerfis()}}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function chaveNome(nome){return nome.replace(/[.#$[\]\/]/g,'_')}
function formatData(d){if(!d)return'';const [a,m,di]=d.split('-');return `${di}/${m}/${a}`}
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.style.display='block';clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.style.display='none',2600)}
function atualizarConexao(ok){const el=document.getElementById('sync-status');if(!el)return;el.className='sync-status '+(ok?'online':'offline');el.textContent=ok?'● Sincronizado':'● Sem conexão'}
window.addEventListener('online',()=>atualizarConexao(true));window.addEventListener('offline',()=>atualizarConexao(false));
function roleLabel(){return window.isAdmin?'Administrador':window.roleLouvor==='visualizacao'?'Visualização':'Responsável'}
function podeEditarChamada(){return window.isAdmin||window.roleLouvor==='responsavel'}
function aplicarPermissoes(){document.querySelectorAll('.admin-tab').forEach(x=>x.style.display=window.isAdmin?'block':'none');document.getElementById('admin-member-tools').style.display=window.isAdmin?'block':'none';document.getElementById('member-permission-note').style.display=window.isAdmin?'none':'block';document.getElementById('btn-salvar-chamada').style.display=podeEditarChamada()?'block':'none';document.getElementById('hero-role').textContent='🔐 '+roleLabel();renderTudo()}
function erroBanco(e,tipo){console.error(e);atualizarConexao(false);if(tipo==='registros')document.getElementById('lista-chamada-salva').innerHTML='<div class="muted center">Erro ao acessar registros. Confira a conexão e as regras do Firebase.</div>'}

function listaMembros(){return Object.values(window.integrantesCadastrados||{}).map(m=>m&&m.nome).filter(Boolean).sort((a,b)=>a.localeCompare(b,'pt-BR'))}
function carregarTudoDaData(){montarRascunho();renderChamadaSalva();gerarFolhaDiaria();renderHistorico()}
function montarRascunho(){const data=document.getElementById('ensaio-data').value,salvos=(window.todosOsDados||{})[data]||{};rascunhoChamada={};listaMembros().forEach(nome=>{const s=salvos[chaveNome(nome)];rascunhoChamada[chaveNome(nome)]={nome,status:s?.status||'',justificado:s?.justificado||'nao',motivo:s?.motivo||''}});renderChamadaRapida()}
function renderChamadaRapida(){const arr=Object.values(rascunhoChamada);const box=document.getElementById('lista-chamada-rapida');if(!arr.length){box.innerHTML='<div class="muted center">Cadastre integrantes na aba Membros.</div>';document.getElementById('quick-progress').textContent='0/0 marcados';return}box.innerHTML=arr.map(m=>{const precisa=m.status==='atrasado'||m.status==='ausente';const detalhe=precisa&&m.justificado==='sim'?`<div class="quick-detail">✓ Justificado${m.motivo?': '+esc(m.motivo):''}</div>`:precisa&&m.motivo?`<div class="quick-detail">${esc(m.motivo)}</div>`:'';return `<div class="quick-member ${m.status?'':'unmarked'}"><div><div class="quick-name">${esc(m.nome)}</div>${detalhe}</div><div class="quick-actions"><button class="qbtn p ${m.status==='presente'?'active':''}" onclick='marcarRapido(${JSON.stringify(m.nome)},"presente")' title="Presente">✓</button><button class="qbtn a ${m.status==='atrasado'?'active':''}" onclick='marcarRapido(${JSON.stringify(m.nome)},"atrasado")' title="Atrasado">A</button><button class="qbtn f ${m.status==='ausente'?'active':''}" onclick='marcarRapido(${JSON.stringify(m.nome)},"ausente")' title="Faltou">F</button>${precisa?`<button class="qbtn note ${m.justificado==='sim'||m.motivo?'active':''}" onclick='editarJustificativaRapida(${JSON.stringify(m.nome)})' title="Justificativa">📝</button>`:''}</div></div>`}).join('');const marcados=arr.filter(x=>x.status).length;document.getElementById('quick-progress').textContent=`${marcados}/${arr.length} marcados`}
function marcarRapido(nome,status){if(!podeEditarChamada())return;const k=chaveNome(nome),atual=rascunhoChamada[k];if(!atual)return;atual.status=atual.status===status?'':status;if(status==='presente'||!atual.status){atual.justificado='nao';atual.motivo=''};renderChamadaRapida()}
function editarJustificativaRapida(nome){if(!podeEditarChamada())return;const m=rascunhoChamada[chaveNome(nome)];if(!m||m.status==='presente'||!m.status)return;const just=confirm(`${nome}: a ${m.status==='atrasado'?'chegada atrasada':'falta'} foi justificada?`);m.justificado=just?'sim':'nao';const motivo=prompt('Motivo (opcional):',m.motivo||'');if(motivo!==null)m.motivo=motivo.trim();renderChamadaRapida()}
function marcarTodos(status){if(!podeEditarChamada())return;Object.values(rascunhoChamada).forEach(m=>{m.status=status;m.justificado='nao';m.motivo=''});renderChamadaRapida()}
function limparMarcacoes(){if(!podeEditarChamada())return;Object.values(rascunhoChamada).forEach(m=>{m.status='';m.justificado='nao';m.motivo=''});renderChamadaRapida()}
async function salvarChamadaRapida(){if(!podeEditarChamada()){alert('Seu perfil é somente visualização.');return}const data=document.getElementById('ensaio-data').value,arr=Object.values(rascunhoChamada),faltando=arr.filter(m=>!m.status);if(faltando.length){alert(`Ainda faltam ${faltando.length} integrante(s) para marcar.`);return}const atual=(window.todosOsDados||{})[data]||{},extras={};Object.entries(atual).forEach(([k,v])=>{if(!rascunhoChamada[k])extras[k]=v});const payload={...extras};arr.forEach(m=>payload[chaveNome(m.nome)]={nome:m.nome,status:m.status,justificado:m.justificado||'nao',motivo:m.motivo||''});try{await window.dbSet(window.dbRef(window.db,`registros_louvor/${data}`),payload);await registrarAuditoria('chamada_salva',`Chamada de ${formatData(data)} salva (${arr.length} integrantes)`);toast('Chamada salva com sucesso.')}catch(e){console.error(e);alert('Não foi possível salvar a chamada. Verifique suas permissões.')}}

function selecionarOpcao(s){statusSelecionado=s;['p','a','f'].forEach(x=>document.getElementById('lbl-'+x).className='status-btn');document.getElementById('lbl-'+(s==='presente'?'p':s==='atrasado'?'a':'f')).classList.add(s==='presente'?'selected-p':s==='atrasado'?'selected-a':'selected-f');document.getElementById('box-justificativa').style.display=s==='presente'?'none':'block'}
function selecionarJustificativa(v){justificativaSelecionada=v;document.getElementById('j-sim').classList.toggle('active',v==='sim');document.getElementById('j-nao').classList.toggle('active',v==='nao')}
async function adicionarAvulso(){if(!podeEditarChamada()){alert('Seu perfil é somente visualização.');return}const nome=document.getElementById('input-busca').value.trim(),data=document.getElementById('ensaio-data').value,motivo=document.getElementById('input-motivo').value.trim();if(!nome)return alert('Digite um nome.');const obj={nome,status:statusSelecionado,justificado:statusSelecionado==='presente'?'nao':justificativaSelecionada,motivo:statusSelecionado==='presente'?'':motivo};try{await window.dbSet(window.dbRef(window.db,`registros_louvor/${data}/${chaveNome(nome)}`),obj);await registrarAuditoria('registro_avulso',`${nome} adicionado em ${formatData(data)}`);document.getElementById('input-busca').value='';document.getElementById('input-motivo').value='';toast('Registro adicionado.')}catch(e){alert('Não foi possível salvar.')}}
async function removerDoFirebase(nome){if(!podeEditarChamada())return;if(!confirm(`Remover ${nome} desta chamada?`))return;try{const data=document.getElementById('ensaio-data').value;await window.dbRemove(window.dbRef(window.db,`registros_louvor/${data}/${chaveNome(nome)}`));await registrarAuditoria('registro_removido',`${nome} removido de ${formatData(data)}`)}catch(e){alert('Não foi possível remover.')}}